export const person = {
    user: {
        id: 12345,
        name: "عمر محمد",
        location: "مصر - الإسكندرية",
        email: "omar@gmail.com",
        phone: "01281599957",
        avatar_url: "/images/profile.png",
        stats: {
            follows: "9",
            subscriptions: "2",
            donations_count: "15",
            total_donations_amount: "10500",
        },
    },
    donation_history: [
        {
            id: 1,
            title: "تبرع بـ 5 جنيهات لمشروع رسالة",
            amount: 5,
            currency: "EGP",
            created_at: "2025-01-05T10:20:00Z",
            time_ago: "منذ شهر",
        },
        {
            id: 2,
            title: "تبرع بـ 5 جنيهات لمشروع رسالة",
            amount: 5,
            currency: "EGP",
            created_at: "2025-01-05T10:20:00Z",
            time_ago: "منذ شهر",
        },
        {
            id: 3,
            title: "تبرع بـ 5 جنيهات لمشروع رسالة",
            amount: 5,
            currency: "EGP",
            created_at: "2025-01-05T10:20:00Z",
            time_ago: "منذ شهر",
        },
        {
            id: 4,
            title: "تبرع بـ 5 جنيهات لمشروع رسالة",
            amount: 5,
            currency: "EGP",
            created_at: "2025-01-05T10:20:00Z",
            time_ago: "منذ شهر",
        },
        {
            id: 5,
            title: "تبرع بـ 5 جنيهات لمشروع رسالة",
            amount: 5,
            currency: "EGP",
            created_at: "2025-01-05T10:20:00Z",
            time_ago: "منذ شهر",
        },
    ],
};

export const atharData = {
    follows: [
        { id: 1, name: "جمعية رسالة", avatar_url: "/images/athar1.png" },
        { id: 2, name: "جمعية الأورمان", avatar_url: "/images/athar2.png" },
        { id: 3, name: "جمعية حياة", avatar_url: "/images/athar3.png" },
        { id: 4, name: "جمعية الخير", avatar_url: "/images/athar4.png" },
        { id: 5, name: "جمعية أهل مصر", avatar_url: "/images/athar5.png" },
        { id: 6, name: "مؤسسة مصر الخير", avatar_url: "/images/athar6.png" },
    ],

    donations: [
        {
            id: 1,
            campaign: "دعم الأيتام في رمضان",
            charity: "جمعية رسالة",
            imgSrc: "/images/athar1.png",
            amount: 500,
            date: "2025-11-25", // أمس
        },
        {
            id: 2,
            campaign: "بناء مدرسة في الصعيد",
            charity: "جمعية الأورمان",
            imgSrc: "/images/athar2.png",
            amount: 1000,
            date: "2025-11-24",
        },
        {
            id: 3,
            campaign: "علاج أطفال السرطان",
            charity: "جمعية حياة",
            imgSrc: "/images/athar3.png",
            amount: 750,
            date: "2025-11-20",
        },
        {
            id: 4,
            campaign: "إغاثة غزة الشتوية",
            charity: "جمعية الخير",
            imgSrc: "/images/athar4.png",
            amount: 2000,
            date: "2025-11-18",
        },
        {
            id: 5,
            campaign: "كفالة 10 أسر محتاجة",
            charity: "جمعية أهل مصر",
            imgSrc: "/images/athar5.png",
            amount: 3000,
            date: "2025-11-10",
        },
        {
            id: 6,
            campaign: "تجهيز عروسين محتاجين",
            charity: "جمعية رسالة",
            imgSrc: "/images/athar1.png",
            amount: 1500,
            date: "2025-11-08",
        },
        {
            id: 7,
            campaign: "حفر بئر في أفريقيا",
            charity: "مؤسسة مصر الخير",
            imgSrc: "/images/athar6.png",
            amount: 5000,
            date: "2025-10-28", // الشهر اللي فات
        },
        {
            id: 8,
            campaign: "دعم مرضى الفشل الكلوي",
            charity: "جمعية حياة",
            imgSrc: "/images/athar3.png",
            amount: 800,
            date: "2025-09-15", // من شهرين
        },
        {
            id: 9,
            campaign: "توزيع بطاطين الشتاء",
            charity: "جمعية الأورمان",
            imgSrc: "/images/athar2.png",
            amount: 600,
            date: "2025-01-20", // السنة دي بس من شهور
        },
        {
            id: 10,
            campaign: "رعاية 5 أيتام لمدة سنة",
            charity: "جمعية رسالة",
            imgSrc: "/images/athar1.png",
            amount: 12000,
            date: "2024-12-01", // السنة اللي فاتت
        },
    ],
};

export const notifications = [
    {
        id: 1,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 2,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 3,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 4,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 5,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 6,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 7,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 8,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 9,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 10,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 100,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 11,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 12,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 13,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 14,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 15,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 16,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 17,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 18,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 19,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 20,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 21,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 22,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 23,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 24,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 25,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 26,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 27,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 28,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 29,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 30,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
    {
        id: 31,
        message: "تبرع بـ 5 جنيهات لمشروع رسالة",
        sender: "جمعية رسالة",
        created_at: "2025-01-05T10:20:00Z",
        time_ago: "منذ شهر",
    },
];

export const info = {
    first_name: "عمر",
    last_name: "محمد",
    country: "مصر",
    city: "الإسكندرية",
    email: "omar@gmail.com",
    password: "jfakjfadj",
    avatar_url: "",
};

export const charityInfo = {
    name: "جمعية اهل مصر",
    description:
        " منصة رقمية شفافة تربط بين الجمعيات الخيرية الموثوق والمتبرعين، لتحقيق أقصى استفادة من كل جنيه يتم التبرع به",
    country: "مصر",
    city: "القاهرة",
    balance: 15000,
    followers: 150,
    campaigns: 8,
    status: "Active",
    profileImage: "",
};

export const charities = [
    {
        id: 1,
        name: "جمعية رسالة",
        description: "جمعية خيرية تهدف لدعم المحتاجين.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 3,
    },
    {
        id: 2,
        name: "جمعية الأورمان",
        description: "تساعد في علاج المرضى ورعاية الأيتام.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 5,
    },
    {
        id: 3,
        name: "جمعية مصر الخير",
        description: "تهدف لتنمية المجتمع في مختلف المجالات.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 2,
    },
    {
        id: 4,
        name: "جمعية الشفا",
        description: "متخصصة في تقديم المساعدات الطبية.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 4,
    },
    {
        id: 5,
        name: "جمعية سند",
        description: "جمعية خيرية لرعاية ذوي الاحتياجات.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 1,
    },
    {
        id: 6,
        name: "جمعية بسمة",
        description: "توفر الغذاء والكساء للأسر الفقيرة.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 0,
    },
    {
        id: 7,
        name: "جمعية كفالة اليتيم",
        description: "ترعى الأيتام وتوفر لهم حياة كريمة.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 6,
    },
    {
        id: 8,
        name: "جمعية دار الرحمة",
        description: "دار مسنين تقدم خدمات رعاية كاملة.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 2,
    },
    {
        id: 9,
        name: "جمعية إغاثة",
        description: "متخصصة في إغاثة المتضررين من الكوارث.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 7,
    },
    {
        id: 10,
        name: "جمعية العطاء",
        description: "توزيع مساعدات على المحتاجين يوميًا.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 3,
    },
    {
        id: 11,
        name: "جمعية نور الحياة",
        description: "تركز على مكافحة العمى وعلاج العيون.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 4,
    },
    {
        id: 12,
        name: "جمعية صدقة",
        description: "منظمة خيرية لدعم الأسر صعبة المعيشة.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 1,
    },
    {
        id: 13,
        name: "جمعية عيون الخير",
        description: "عمليات مجانية للفقراء.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 8,
    },
    {
        id: 14,
        name: "جمعية معًا",
        description: "مشاريع صغيرة للأسر المحتاجة.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 2,
    },
    {
        id: 15,
        name: "جمعية الأيادي البيضاء",
        description: "حملات تطوعية شبابية.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 0,
    },
    {
        id: 16,
        name: "جمعية البر والتقوى",
        description: "توزيع لحوم ووجبات يومية.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 5,
    },
    {
        id: 17,
        name: "جمعية الأمل",
        description: "برامج لمحو الأمية وتعليم الصغار.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 3,
    },
    {
        id: 18,
        name: "جمعية بسمة أمل",
        description: "رعاية أطفال السرطان.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 6,
    },
    {
        id: 19,
        name: "جمعية سوا",
        description: "خدمات اجتماعية متنوعة.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 2,
    },
    {
        id: 20,
        name: "جمعية خير وبركة",
        description: "رعاية الأسر متدنية الدخل.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 1,
    },
    {
        id: 21,
        name: "جمعية المقصد",
        description: "دعم الطلاب غير القادرين.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 4,
    },
    {
        id: 22,
        name: "جمعية اليسر",
        description: "توزيع مساعدات شهرية.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 5,
    },
    {
        id: 23,
        name: "جمعية رحماء",
        description: "مساعدات طبية واجتماعية.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 2,
    },
    {
        id: 24,
        name: "جمعية كيان",
        description: "رعاية فاقدي الرعاية الأسرية.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 7,
    },
    {
        id: 25,
        name: "جمعية حياة",
        description: "كفالات شهرية للفقراء.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 1,
    },
    {
        id: 26,
        name: "جمعية بصمة خير",
        description: "توزيع بطاطين وأغطية الشتاء.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 3,
    },
    {
        id: 27,
        name: "جمعية عطاء بلا حدود",
        description: "تبرعات غذائية مستمرة.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 6,
    },
    {
        id: 28,
        name: "جمعية كفيل",
        description: "متخصصة في كفالة الطفل اليتيم.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 4,
    },
    {
        id: 29,
        name: "جمعية بسمة خير",
        description: "رعاية الأطفال ذوي الاحتياجات الخاصة.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 2,
    },
    {
        id: 30,
        name: "جمعية فاعل خير",
        description: "خدمات مجتمعية وبيئية.",
        imageBase64: "data:image/jpeg;base64,FAKE_BASE64_IMAGE",
        campaignsCount: 1,
    },
];

export const campaigns = [
    {
        id: 1,
        title: "دعم تعليم الأطفال في المناطق الفقيرة",
        description: "توفير مستلزمات تعليمية لـ 500 طفل غير قادر.",
        raisedAmount: 12000,
        goalAmount: 30000,
        startDate: "2025-01-01",
        endDate: "2025-03-01",
        charityName: "جمعية التعليم أولًا",
    },
    {
        id: 2,
        title: "إنقاذ حياة مريض قلب",
        description: "جمع تبرعات لعملية قلب عاجلة.",
        raisedAmount: 8000,
        goalAmount: 20000,
        startDate: "2025-02-10",
        endDate: "2025-04-10",
        charityName: "جمعية الرحمة الطبية",
    },
    {
        id: 3,
        title: "كسوة الشتاء",
        description: "توفير ملابس شتوية لـ 1000 أسرة.",
        raisedAmount: 15000,
        goalAmount: 40000,
        startDate: "2025-01-15",
        endDate: "2025-03-01",
        charityName: "جمعية أهل الخير",
    },
    {
        id: 4,
        title: "بناء منزل لأسرة فقيرة",
        description: "ترميم منزل غير آدمي لأسرة مكونة من 6 أفراد.",
        raisedAmount: 9000,
        goalAmount: 25000,
        startDate: "2025-02-01",
        endDate: "2025-05-01",
        charityName: "جمعية إعمار",
    },
    {
        id: 5,
        title: "إفطار صائم",
        description: "تجهيز وجبات إفطار لـ 10,000 صائم.",
        raisedAmount: 45000,
        goalAmount: 100000,
        startDate: "2025-02-20",
        endDate: "2025-04-20",
        charityName: "جمعية الخير",
    },
    {
        id: 6,
        title: "حفر بئر مياه",
        description: "حفر بئر مياه في قرية لا تملك مصدرًا للمياه.",
        raisedAmount: 6000,
        goalAmount: 20000,
        startDate: "2025-01-05",
        endDate: "2025-06-01",
        charityName: "جمعية سقيا",
    },
    {
        id: 7,
        title: "دعم مرضى السرطان",
        description: "توفير جلسات علاج لـ 50 طفل.",
        raisedAmount: 20000,
        goalAmount: 60000,
        startDate: "2025-02-01",
        endDate: "2025-07-01",
        charityName: "مستشفى الشفاء",
    },
    {
        id: 8,
        title: "تجهيز عرائس",
        description: "مساعدة 20 عروسة غير قادرة.",
        raisedAmount: 5000,
        goalAmount: 30000,
        startDate: "2025-03-01",
        endDate: "2025-06-01",
        charityName: "جمعية اليسر",
    },
    {
        id: 9,
        title: "إعمار مسجد",
        description: "ترميم مسجد متهالك في منطقة نائية.",
        raisedAmount: 10000,
        goalAmount: 50000,
        startDate: "2025-01-10",
        endDate: "2025-07-10",
        charityName: "جمعية عمارة المساجد",
    },
    {
        id: 10,
        title: "إطعام محتاج",
        description: "توفير 3000 وجبة للفقراء.",
        raisedAmount: 25000,
        goalAmount: 50000,
        startDate: "2025-02-15",
        endDate: "2025-05-01",
        charityName: "بنك الطعام",
    },

    ...Array.from({ length: 20 }, (_, i) => ({
        id: 11 + i,
        title: `حملة خير رقم ${i + 1}`,
        description: `وصف تفصيلي لحملة خير رقم ${i + 1} لمساعدة المحتاجين.`,
        raisedAmount: Math.floor(Math.random() * 30000),
        goalAmount: 20000 + Math.floor(Math.random() * 60000),
        startDate: "2025-01-01",
        endDate: "2025-06-01",
        charityName: "جمعية الخير العامة",
    })),
];

export const campaigns2 = [];

export const charityProfileInfo = {
    id: 1,
    name: "جمعية أثر الإنسانية",
    description:
        "جمعية غير ربحية تعمل على تحسين حياة الأسر الأكثر احتياجًا من خلال حملات مستمرة وبرامج دعم مجتمعي، وترك أثر حقيقي في حياة الناس.",
    country: "مصر",
    city: "القاهرة",
    followers: 3250,
    campaignsCount: 18,
    profileImage: "/images/charity-logo.jpg",
};

export const charityProfileData = {
    name: "جمعية الأمل الخيرية",
    logo: "https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=400",
    coverImage:
        "https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
        "جمعية الأمل الخيرية هي منظمة غير ربحية تهدف إلى مساعدة المحتاجين وتوفير الدعم للأسر الفقيرة. نعمل على تحسين حياة المجتمعات من خلال برامج التعليم والصحة والإغاثة الإنسانية.",
    followersCount: 12453,
    campaignsCount: 47,

    campaigns: [
        {
            id: 1,
            title: "كساء الشتاء",
            description: "توفير ملابس شتوية لعدد 300 أسرة محتاجة.",
            raisedAmount: 15000,
            goalAmount: 40000,
            startDate: "2025-01-05",
            endDate: "2025-03-01",
            charityName: "جمعية أثر الإنسانية",
        },
        {
            id: 2,
            title: "حملة توفير علاج",
            description: "شراء أدوية شهرية لـ 120 مريضًا من كبار السن.",
            raisedAmount: 32000,
            goalAmount: 60000,
            startDate: "2025-02-10",
            endDate: "2025-05-20",
            charityName: "جمعية أثر الإنسانية",
        },
        {
            id: 3,
            title: "مساعدة الأيتام",
            description: "توفير تكاليف التعليم لـ 80 طفل يتيم.",
            raisedAmount: 42000,
            goalAmount: 80000,
            startDate: "2025-03-01",
            endDate: "2025-08-01",
            charityName: "جمعية أثر الإنسانية",
        },
        {
            id: 4,
            title: "سقيا الماء",
            description: "حفر بئر مياه نظيفة في قرية نائية.",
            raisedAmount: 18000,
            goalAmount: 50000,
            startDate: "2025-02-01",
            endDate: "2025-09-01",
            charityName: "جمعية أثر الإنسانية",
        },
        {
            id: 5,
            title: "إطعام محتاج",
            description: "توزيع 500 وجبة غذائية يوميًا لمدة شهر.",
            raisedAmount: 60000,
            goalAmount: 90000,
            startDate: "2025-01-15",
            endDate: "2025-02-15",
            charityName: "جمعية أثر الإنسانية",
        },
        {
            id: 6,
            title: "ترميم منازل",
            description: "إعادة بناء أسقف 20 منزل متهالك.",
            raisedAmount: 25000,
            goalAmount: 70000,
            startDate: "2025-01-15",
            endDate: "2025-02-15",
            charityName: "جمعية أثر الإنسانية",
        },
    ],

    mediaPosts: [
        {
            id: 1,
            image: "https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "زيارة ميدانية لتوزيع المساعدات على الأسر المحتاجة",
            likes: 342,
        },
        {
            id: 2,
            image: "https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "فعالية توزيع الحقائب المدرسية للطلاب",
            likes: 289,
        },
        {
            id: 3,
            image: "https://images.pexels.com/photos/6995247/pexels-photo-6995247.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "إفطار جماعي للصائمين في المسجد",
            likes: 521,
        },
        {
            id: 4,
            image: "https://images.pexels.com/photos/6646914/pexels-photo-6646914.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "حملة الشتاء الدافئ - توزيع البطانيات",
            likes: 413,
        },
        {
            id: 5,
            image: "https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "زيارة ميدانية لتوزيع المساعدات على الأسر المحتاجة",
            likes: 342,
        },
        {
            id: 6,
            image: "https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "فعالية توزيع الحقائب المدرسية للطلاب",
            likes: 289,
        },
        {
            id: 7,
            image: "https://images.pexels.com/photos/6995247/pexels-photo-6995247.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "إفطار جماعي للصائمين في المسجد",
            likes: 521,
        },
        {
            id: 8,
            image: "https://images.pexels.com/photos/6646914/pexels-photo-6646914.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "حملة الشتاء الدافئ - توزيع البطانيات",
            likes: 413,
        },
        {
            id: 9,
            image: "https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "زيارة ميدانية لتوزيع المساعدات على الأسر المحتاجة",
            likes: 342,
        },
        {
            id: 10,
            image: "https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "فعالية توزيع الحقائب المدرسية للطلاب",
            likes: 289,
        },
        {
            id: 11,
            image: "https://images.pexels.com/photos/6995247/pexels-photo-6995247.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "إفطار جماعي للصائمين في المسجد",
            likes: 521,
        },
        {
            id: 12,
            image: "https://images.pexels.com/photos/6646914/pexels-photo-6646914.jpeg?auto=compress&cs=tinysrgb&w=600",
            caption: "حملة الشتاء الدافئ - توزيع البطانيات",
            likes: 413,
        },
    ],
};

export const forms = [
    {
        id: 1,
        type: "volunteer",
        description: "أرغب بالمشاركة في الأنشطة الميدانية القادمة.",
        fullName: "محمد سالم أحمد",
        phone: "0555555555",
        message:
            "أود المساعدة في توزيع المساعدات وتنظيم الفعاليات الخيرية في المنطقة الشرقية.",
        date: "2025-11-29T10:30:00",
        status: "new",
        read: false,
    },
    {
        id: 2,
        type: "merchant",
        description: "التعاون في حملة تبرع بالملابس الجديدة.",
        fullName: "شركة الهدى للملابس",
        phone: "0544444444",
        message:
            "نرغب في التبرع بكميات كبيرة من الملابس الشتوية الجديدة للمحتاجين.",
        date: "2025-11-28T14:20:00",
        status: "replied",
        read: true,
    },
    {
        id: 3,
        type: "donation",
        description: "تبرع نوعي: أجهزة كهربائية مستعملة بحالة ممتازة.",
        fullName: "سارة منصور",
        phone: "0533333333",
        message:
            "لدي ثلاجة وغسالة ومكيف بحالة ممتازة أود التبرع بها لأسرة محتاجة.",
        date: "2025-11-27T09:15:00",
        status: "pending",
        read: false,
    },
    {
        id: 4,
        type: "volunteer",
        description: "متطوع في مجال التدريس والدروس الخصوصية.",
        fullName: "عبدالله الحربي",
        phone: "0522222222",
        message:
            "معلم رياضيات متقاعد، أرغب في تقديم دروس مجانية للطلاب المحتاجين.",
        date: "2025-11-26T16:45:00",
        status: "replied",
        read: true,
    },
    {
        id: 5,
        type: "donation",
        description: "تبرع بكتب ومراجع علمية وأدبية.",
        fullName: "فاطمة العتيبي",
        phone: "0511111111",
        message:
            "مكتبة منزلية كاملة تحتوي على أكثر من 500 كتاب في مختلف المجالات.",
        date: "2025-11-25T11:30:00",
        status: "new",
        read: false,
    },
    {
        id: 6,
        type: "merchant",
        description: "مخبز يرغب في التبرع بالخبز يوميًا.",
        fullName: "مخبز النور",
        phone: "0500000000",
        message:
            "نود التعاون في توفير الخبز الطازج يوميًا للأسر المتعففة في الحي.",
        date: "2025-11-24T08:00:00",
        status: "pending",
        read: false,
    },
];
